version: '3.1'
services:
  db:
    container_name: "console_chat_db"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: spit-preface-inflict-nonsense-hooves-heaven-noted-pitcher-skyway-choice
    ports:
      - "3308:3306"
    volumes:
      - .consolechat-db:/var/lib/mysql
  phpmyadmin:
    container_name: "visualize_console_chat_db"
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
